kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  # these labels are for deployment resources
  labels: 
    app: nginx
	tier: frontend
	purpose: deployment
spec:
 replicas: 3
  selector:
   matchLabels:
    app: nginx
	tier: frontend
	purpose: deployment
  template:
  metadata:
	 labels:
	   app: nginx
	   tier: frontend
	   purpose: deployment
	spec:
	 containers:
	 - name: nginx
	   image: nginx:1.14.2
	   ports:
	   - containerPort: 80